name: Main Workflow

on:
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - 'master'
    paths:
      - './README.md'

jobs:
  push_markdown_job:
    runs-on: ubuntu-latest
    name: Push Markdown to Notion
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Push Markdown to Notion
        uses: JoshStern/push-md-to-notion@v0.2
        id: push_markdown
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
