name: Main Workflow

on:
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - 'master'
    paths:
      - './README.md'

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: github-markdown-to-notion-db
        uses: vdubois/github-markdown-to-notion-db@54bb95aab47ddbe148ad77a2e5f6bab411e73df0
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          GITHUB_MD_PATH: "docs"
