name: Main Workflow

on:
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - 'master'
    paths:
      - './README.md'

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gallery Fake
        uses: litencatt/gallery-fake@v0.4.0
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          GITHUB_MD_PATH: "docs"
